name             'windows_print'
maintainer       'Texas A&M'
maintainer_email 'derekgroh@github.com'
license          'MIT'
description      'Installs/Configures print'
version          '1.0.2'
issues_url       'https://github.com/TAMUArch/cookbook.windows_print/issues'
source_url       'https://github.com/TAMUArch/cookbook.windows_print'
supports         'windows'
chef_version     '> 14'
