name             'windows_print'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'MIT'
description      'Installs/Configures print'
version          '1.0.2'
source_url       'https://github.com/sous-chefs/windows_print'
issues_url       'https://github.com/sous-chefs/windows_print/issues'
supports         'windows'
chef_version     '> 14'
