---
name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@0.0.3

  integration-windows-2016:  # EOL March 15
    needs: lint-unit
    runs-on: windows-2016
    strategy:
      matrix:
        os:
          - 'windows-2016'
        suite:
          - 'default'
          - 'internet-printing'
          - 'lpd-service'
          - 'resources'
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: test-kitchen
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen_exec.yml
          # ACTIONS_ALLOW_UNSECURE_COMMANDS: true  # allow path editing
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}

  integration-windows-2019:
    needs: lint-unit
    runs-on: windows-2019
    strategy:
      matrix:
        os:
          - 'windows-2019'
        suite:
          - 'default'
          - 'internet-printing'
          - 'lpd-service'
          - 'resources'
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: test-kitchen
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen_exec.yml
          # ACTIONS_ALLOW_UNSECURE_COMMANDS: true  # allow path editing
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
